### ISSUE TITLE
replace iframed calendar with deprecation/removal message

### ISSUE THREAD

**Issue by stopfstedt** [ilios/moodle-block-ilios#17]
working draft screenshot:

![Embedded calendar on course page](https://user-images.githubusercontent.com/1410427/33958779-5e093964-dffa-11e7-81d3-8b2916dcc32c.png)

![standalone page with embedded calendar](https://user-images.githubusercontent.com/1410427/33958803-6db6aa2c-dffa-11e7-9098-8a5c94fdfa2b.png)

**Comment by stopfstedt** [comment]
@saschaben please provide exact wording that will take the place of the embedded/iframed calendar. please note that this message can contain markup (e.g. offsite links).
the message will be displayed to all users that are able to access the course, not just course administrators, but also students/learners.

**Comment by jrjohnson** [comment]
I think we should say please use the 'Ilios Dashboard' activity. LTI doesn't really mean anything here.

**Comment by stopfstedt** [comment]
i wonder if we should omit any reference to the replacement tool altogether, as this only pertains to course builders and not consumers. the students taking the course should be instructed in such a manner.

**Comment by jrjohnson** [comment]
Results of offline discussion, we should provide a longer message targeting individuals.

"If you are a student needing access to your calendar, click HERE.  If you are the manager of this course and would like to display a calendar in this place please contact BLAH."

**Comment by stopfstedt** [comment]
Finalized version of this message, h/t Sean.

"If you are a student needing access to your calendar, please visit https://curriculum.ucsf.edu/. If you are the manager of this course and would like help adding the new Ilios activity please contact [the Learning Tech Group](https://learningtech.library.ucsf.edu/-/contact/)."
